// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { pathToFileURL } from 'url';
import { API_NAMESPACE_MARKER } from '../api.js';

/**
 * Generate browser-safe client code from backend exports.
 *
 * Sets up global collectors (__BLOCKS_CLIENT_MIDDLEWARE__) before importing
 * the backend so that Building Block constructors can register their
 * middleware. After import, reads the collected specifiers and emits
 * import statements + ApiNamespace proxy exports.
 */
export async function generateClientCode(foundationPath: string): Promise<string> {
  // Set up global collector if not already present (dev server may have already done this)
  const collectorAlreadyActive = Array.isArray((globalThis as any).__BLOCKS_CLIENT_MIDDLEWARE__);
  if (!collectorAlreadyActive) {
    (globalThis as any).__BLOCKS_CLIENT_MIDDLEWARE__ = [];
  }

  const backend = await import(pathToFileURL(foundationPath).href);

  // Read collected middleware and clean up
  const middleware: string[] = (globalThis as any).__BLOCKS_CLIENT_MIDDLEWARE__;
  delete (globalThis as any).__BLOCKS_CLIENT_MIDDLEWARE__;

  const imports = new Set<string>();
  const lines: string[] = [];
  const namespaceNames: string[] = [];

  imports.add(`import { ApiNamespaceClient as __BLOCKS_ApiNamespaceClient__ } from '@aws-blocks/blocks/client';`);

  for (const specifier of middleware) {
    imports.add(`import '${specifier}';`);
  }

  // Emit ApiNamespace proxy exports
  for (const [name, value] of Object.entries(backend)) {
    if (name.startsWith('_')) continue;

    const isApiNamespace = typeof (value as any)?.[API_NAMESPACE_MARKER] === 'string';
    if (isApiNamespace) {
      lines.push(`export const ${name} = __BLOCKS_ApiNamespaceClient__('${name}');`);
      namespaceNames.push(name);
      continue;
    }

    // Fallback: any exported function/object that isn't a Scope gets a proxy.
    const isScope = typeof (value as any)?.id === 'string' && typeof (value as any)?.fullId === 'string';
    if (isScope) continue;

    // Fallback: any exported function/object gets an ApiNamespace proxy.
    if ((typeof value === 'function' || typeof value === 'object') && value !== null) {
      lines.push(`export const ${name} = __BLOCKS_ApiNamespaceClient__('${name}');`);
      namespaceNames.push(name);
    }
  }

  // Emit generateClient — creates new ApiNamespaceClient instances with the given url
  const nsEntries = namespaceNames.map(n => `    ${n}: __BLOCKS_ApiNamespaceClient__('${n}', config),`).join('\n');
  lines.push('');
  lines.push(`export const generateClient = (config) => ({\n${nsEntries}\n});`);

  const header = [
    '// ============================================================',
    '// AUTO-GENERATED FILE — DO NOT EDIT',
    '//',
    '// This file is generated by the Blocks dev server / build process.',
    '// Any manual changes will be overwritten on the next build.',
    '// ============================================================',
  ];

  return [...header, '', ...imports, '', ...lines].join('\n');
}

/**
 * Generate client code and write it to the aws-blocks subpackage.
 */
export async function writeClientCode(foundationPath: string, outputPath: string): Promise<void> {
  const code = await generateClientCode(foundationPath);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, code);
}
