// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import type { DatabaseEngine } from '@aws-blocks/data-common';

interface ColumnInfo {
  table_name: string;
  column_name: string;
  data_type: string;
  is_nullable: string;
  column_default: string | null;
}

/** PostgreSQL type → TypeScript type mapping. */
const PG_TO_TS: Record<string, string> = {
  'integer': 'number',
  'bigint': 'number',
  'smallint': 'number',
  'decimal': 'number',
  'numeric': 'number',
  'real': 'number',
  'double precision': 'number',
  'serial': 'number',
  'bigserial': 'number',
  'text': 'string',
  'character varying': 'string',
  'varchar': 'string',
  'char': 'string',
  'character': 'string',
  'uuid': 'string',
  'boolean': 'boolean',
  'timestamp without time zone': 'Date',
  'timestamp with time zone': 'Date',
  'timestamp': 'Date',
  'timestamptz': 'Date',
  'date': 'Date',
  'time': 'string',
  'json': 'unknown',
  'jsonb': 'unknown',
  'bytea': 'Uint8Array',
};

/** Introspection query for public schema columns. */
const INTROSPECTION_SQL = `
  SELECT table_name, column_name, data_type, is_nullable, column_default
  FROM information_schema.columns
  WHERE table_schema = 'public'
  ORDER BY table_name, ordinal_position
`;

/** Tables starting with this prefix are excluded from type generation. */
const INTERNAL_TABLE_PREFIX = '_';

/**
 * Introspect a database schema and generate TypeScript type definitions.
 *
 * Queries `information_schema.columns` for all public tables, maps PostgreSQL
 * types to TypeScript types, and produces interface definitions.
 *
 * @param engine - A DatabaseEngine to run the introspection query against
 * @returns TypeScript source code with table interfaces and a Database aggregate type
 *
 * @example
 * const engine = new PGliteEngine('.bb-data');
 * const types = await generateTypes(engine);
 * fs.writeFileSync('./types/database.ts', types);
 */
export async function generateTypes(engine: DatabaseEngine): Promise<string> {
  const columns = await engine.query<ColumnInfo>(INTROSPECTION_SQL);

  const tables = new Map<string, ColumnInfo[]>();

  for (const col of columns) {
    if (col.table_name.startsWith(INTERNAL_TABLE_PREFIX)) continue;

    if (!tables.has(col.table_name)) {
      tables.set(col.table_name, []);
    }
    tables.get(col.table_name)!.push(col);
  }

  let output = '// Generated by @aws-blocks/bb-data — do not edit manually\n\n';

  for (const [tableName, cols] of tables) {
    const name = pascalCase(tableName);

    output += `export interface ${name}Table {\n`;
    for (const col of cols) {
      const tsType = pgTypeToTs(col.data_type);
      const nullable = col.is_nullable === 'YES' ? ' | null' : '';
      output += `  ${col.column_name}: ${tsType}${nullable};\n`;
    }
    output += '}\n\n';
  }

  if (tables.size > 0) {
    output += 'export interface Database {\n';
    for (const [tableName] of tables) {
      output += `  ${tableName}: ${pascalCase(tableName)}Table;\n`;
    }
    output += '}\n';
  }

  return output;
}

function pgTypeToTs(pgType: string): string {
  return PG_TO_TS[pgType.toLowerCase()] || 'unknown';
}

function pascalCase(str: string): string {
  return str
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}
