// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Configuration options for the Database Building Block.
 */
import type { ChildLogger } from '@aws-blocks/bb-logger';
export interface DatabaseOptions {
  /** Minimum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  minCapacity?: number;
  /** Maximum Aurora capacity units. Applied by the CDK layer (see infra.ts). */
  maxCapacity?: number;
  /** Database name. Derived from scope.fullId if omitted. */
  databaseName?: string;
  /** Wrap an existing database instead of creating one. */
  connection?: ExternalDatabaseRef;
  /** Path to directory containing numbered `.sql` migration files. */
  migrationsPath?: string;
  /** Runtime schema metadata for crud(). Generated by `db pull`. */
  schema?: import('./crud/types.js').TableSchema;
  /**
   * RLS enforcement policy for this database. Set by `db pull` when introspection
   * detects tables with RLS enabled.
   *
   * **Important:** `'enforce'` currently applies ONLY to `db.crud()` operations
   * (which always route through `withRLS()`). Raw `db.query()` / `db.execute()` /
   * `db.transaction()` calls bypass RLS unless you explicitly use
   * `db.withRLS({ userId })`. If you hand-write queries, you must opt in yourself.
   */
  rlsPolicy?: 'enforce';
  /**
   * CloudFormation removal policy for the Aurora cluster.
   * Use 'destroy' for dev/sandbox, 'retain' (default) for production to prevent data loss.
   * @default 'retain'
   */
  removalPolicy?: 'destroy' | 'retain' | 'snapshot';
	/** Optional logger for internal operations. When omitted, a default Logger at error level is created. */
	logger?: ChildLogger;
}

/**
 * Reference to an external database not managed by this Building Block.
 * Used with `Database.fromExisting()`.
 */
export type ExternalDatabaseRef =
  | { host: string; port?: number; database: string; secretArn: string }
  | { connectionString: string | { get(): Promise<string> } };
