name: blocks_example
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  http: ^1.2.0
  blocks_runtime:
    path: ../packages/blocks_runtime

dev_dependencies:
  build_runner: ^2.4.0
  blocks_codegen:
    path: ../packages/blocks_codegen
