// ============================================================
// AUTO-GENERATED FILE — DO NOT EDIT
//
// This file is generated by the Blocks dev server / build process.
// Any manual changes will be overwritten on the next build. The
// committed copy just gives Vite something importable on the first
// render pass before the dev server finishes its initial generation.
// ============================================================

import { ApiNamespaceClient as __BLOCKS_ApiNamespaceClient__ } from '@aws-blocks/blocks/client';

export const api = __BLOCKS_ApiNamespaceClient__('api');
export const authApi = __BLOCKS_ApiNamespaceClient__('authApi');
export const hello = __BLOCKS_ApiNamespaceClient__('hello');
