// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Integration test: db.crud() + PGliteEngine + RLS.
 *
 * Proves the full CRUD flow with real SQL execution, RLS enforcement,
 * and filter DSL against PGlite (WASM PostgreSQL).
 */
import { test, afterEach } from 'node:test';
import assert from 'node:assert';
import { rmSync } from 'node:fs';
import { PGliteEngine } from '../engines/pglite-engine.js';
import { RLSEnabledDatabase } from '../database.js';
import { createCrudHandlers } from './index.js';
import type { TableSchema } from './types.js';

const TEST_DIR = '.bb-data-crud-integration-' + process.pid;
let engine: PGliteEngine;

const schema: TableSchema = {
  todos: {
    singular: 'todo',
    plural: 'todos',
    primaryKey: 'id',
    columns: ['id', 'content', 'done', 'priority', 'user_id', 'created_at'],
    autoGenerated: ['id', 'created_at'],
  },
};

afterEach(async () => {
  if (engine) await engine.destroy().catch(() => {});
  rmSync(TEST_DIR, { recursive: true, force: true });
});

async function setup(): Promise<RLSEnabledDatabase> {
  engine = new PGliteEngine(TEST_DIR);

  await engine.execute(`DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticated') THEN
      CREATE ROLE authenticated NOLOGIN;
    END IF;
  END $$`);
  await engine.execute(`GRANT USAGE ON SCHEMA public TO authenticated`);

  await engine.execute(`CREATE TABLE todos (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    content TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    priority INTEGER NOT NULL DEFAULT 0,
    user_id TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  )`);
  await engine.execute(`ALTER TABLE todos ENABLE ROW LEVEL SECURITY`);
  await engine.execute(`CREATE POLICY "users_own_todos" ON todos
    FOR ALL TO authenticated
    USING (user_id = (current_setting('request.jwt.claims', true)::json->>'sub'))`);
  await engine.execute(`GRANT SELECT, INSERT, UPDATE, DELETE ON todos TO authenticated`);

  // Seed data
  await engine.execute(
    `INSERT INTO todos (id, content, done, priority, user_id) VALUES
      ('t1', 'User 1 first', false, 1, 'user-1'),
      ('t2', 'User 1 second', true, 5, 'user-1'),
      ('t3', 'User 1 third', false, 3, 'user-1'),
      ('t4', 'User 2 todo', false, 2, 'user-2')`,
  );

  return new RLSEnabledDatabase(engine);
}

function makeCrud(db: RLSEnabledDatabase, userId: string) {
  return createCrudHandlers(db, schema, {
    tables: ['todos'],
    auth: async () => ({ userId, claims: { sub: userId, role: 'authenticated' } }),
  });
}

test('crud integration: listTodos returns only user-1 rows', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos();
  assert.strictEqual(rows.length, 3);
  for (const row of rows) assert.strictEqual(row.user_id, 'user-1');
});

test('crud integration: listTodos with where filter', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos({ where: { done: false } });
  assert.strictEqual(rows.length, 2);
  for (const row of rows) assert.strictEqual(row.done, false);
});

test('crud integration: listTodos with gt operator', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos({ where: { priority: { gt: 2 } } });
  assert.strictEqual(rows.length, 2); // priority 3 and 5
});

test('crud integration: listTodos with orderBy', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos({ orderBy: 'priority:desc' });
  assert.strictEqual(rows[0].priority, 5);
  assert.strictEqual(rows[2].priority, 1);
});

test('crud integration: listTodos with limit', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos({ limit: 2, orderBy: 'priority:asc' });
  assert.strictEqual(rows.length, 2);
  assert.strictEqual(rows[0].priority, 1);
});

test('crud integration: listTodos with select', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos({ select: ['id', 'content'] });
  assert.strictEqual(rows.length, 3);
  // Only selected columns should be present
  assert.ok('id' in rows[0]);
  assert.ok('content' in rows[0]);
  assert.ok(!('done' in rows[0]));
});

test('crud integration: listTodos with or clause', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const rows = await crud.listTodos({ where: { or: [{ done: true }, { priority: { gte: 3 } }] } });
  // done=true (t2, priority 5) OR priority>=3 (t2 priority 5, t3 priority 3)
  assert.strictEqual(rows.length, 2);
});

test('crud integration: getTodo returns single row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const row = await crud.getTodo('t1');
  assert.strictEqual(row.id, 't1');
  assert.strictEqual(row.content, 'User 1 first');
});

test('crud integration: getTodo returns null for other user row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const row = await crud.getTodo('t4'); // belongs to user-2
  assert.strictEqual(row, null);
});

test('crud integration: createTodo inserts and returns row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const row = await crud.createTodo({ content: 'New todo', done: false, priority: 7, user_id: 'user-1' });
  assert.strictEqual(row.content, 'New todo');
  assert.strictEqual(row.priority, 7);
  assert.ok(row.id); // auto-generated
  assert.ok(row.created_at); // auto-generated
});

test('crud integration: updateTodo updates and returns row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const row = await crud.updateTodo('t1', { done: true, priority: 10 });
  assert.strictEqual(row.id, 't1');
  assert.strictEqual(row.done, true);
  assert.strictEqual(row.priority, 10);
});

test('crud integration: updateTodo returns null for other user row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const row = await crud.updateTodo('t4', { done: true }); // belongs to user-2
  assert.strictEqual(row, null);
});

test('crud integration: deleteTodo deletes own row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const result = await crud.deleteTodo('t1');
  assert.strictEqual(result.deleted, true);
  // Verify it's gone
  const row = await crud.getTodo('t1');
  assert.strictEqual(row, null);
});

test('crud integration: deleteTodo cannot delete other user row', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  const result = await crud.deleteTodo('t4'); // belongs to user-2
  assert.strictEqual(result.deleted, false);
});

test('crud integration: user-2 isolation', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-2');
  const rows = await crud.listTodos();
  assert.strictEqual(rows.length, 1);
  assert.strictEqual(rows[0].id, 't4');
});

test('crud integration: exclude removes methods', async () => {
  const db = await setup();
  const crud = createCrudHandlers(db, schema, {
    tables: ['todos'],
    auth: async () => ({ userId: 'user-1', claims: { sub: 'user-1', role: 'authenticated' } }),
    exclude: ['createTodo', 'deleteTodo'],
  });
  assert.ok('listTodos' in crud);
  assert.ok('getTodo' in crud);
  assert.ok('updateTodo' in crud);
  assert.ok(!('createTodo' in crud));
  assert.ok(!('deleteTodo' in crud));
});

test('crud integration: unknown column in where throws', async () => {
  const db = await setup();
  const crud = makeCrud(db, 'user-1');
  await assert.rejects(
    () => crud.listTodos({ where: { nonexistent: true } }),
    /Unknown column: "nonexistent"/,
  );
});
