/**
 * E2E test: db pull introspection + generation + CRUD against a real Supabase database.
 *
 * Tests the actual code path:
 *   1. introspect() against the live schema
 *   2. Verify table detection, PK handling, auth.uid() skipping
 *   3. Generate types/meta via the real generators
 *   4. CRUD operations using the generated tableMeta
 *
 * Requires env vars:
 *   SUPABASE_DB_URL
 *
 * Skips gracefully if not set. No Supabase Auth dependency — uses synthetic
 * userId/claims with withRLS(), matching the post-decoupling OIDC flow.
 */
import { describe, test, before, after } from 'node:test';
import assert from 'node:assert';
import {
  introspect,
  generateTypesFile,
  generateMetaFile,
  generateIndexFile,
} from '../db-pull.js';
import { PgClientEngine } from '../engines/pg-client-engine.js';
import { RLSEnabledDatabase } from '../database.js';
import { createCrudHandlers } from './index.js';

const dbUrl = process.env.SUPABASE_DB_URL;
const skip = !dbUrl;

describe('db pull E2E — introspect + generate + CRUD', { skip }, () => {
  let result: Awaited<ReturnType<typeof introspect>>;
  let engine: PgClientEngine;
  let db: RLSEnabledDatabase;

  // Synthetic user — no Supabase Auth needed. withRLS() sets request.jwt.claims directly.
  const testUser = { userId: 'e2e-test-user-001', claims: { sub: 'e2e-test-user-001' } };

  before(async () => {
    result = await introspect(dbUrl!);
    engine = new PgClientEngine({ connectionString: dbUrl!, ssl: { rejectUnauthorized: false } });
    db = new RLSEnabledDatabase(engine);
  });

  after(async () => {
    await engine?.destroy();
  });

  // ── Introspection assertions ──────────────────────────────────────────

  test('finds expected tables in public schema', () => {
    const names = result.tables.map(t => t.name);
    assert.ok(names.includes('todos'), 'should find todos');
    assert.ok(names.includes('composite_pk_items'), 'should find composite_pk_items');
    assert.ok(names.includes('no_pk_log'), 'should find no_pk_log');
    assert.ok(names.includes('exotic_types'), 'should find exotic_types');
    assert.ok(names.includes('reserved_cols'), 'should find reserved_cols');
    assert.ok(names.includes('jwt_policy_table'), 'should find jwt_policy_table');
  });

  test('detects auth.uid() tables for skipping', () => {
    assert.ok(result.tablesUsingSupabaseAuth.has('todos'), 'todos uses auth.uid()');
    assert.ok(!result.tablesUsingSupabaseAuth.has('jwt_policy_table'), 'jwt_policy_table uses auth.jwt() — should NOT be flagged');
    assert.ok(!result.tablesUsingSupabaseAuth.has('composite_pk_items'), 'composite_pk_items has no RLS');
  });

  test('detects composite primary key', () => {
    const table = result.tables.find(t => t.name === 'composite_pk_items');
    assert.ok(table, 'composite_pk_items should exist');
    assert.ok(Array.isArray(table.primaryKey), 'composite PK should be an array');
    assert.deepStrictEqual((table.primaryKey as string[]).sort(), ['order_id', 'product_id'].sort());
  });

  test('detects no-PK table with empty primaryKey', () => {
    const table = result.tables.find(t => t.name === 'no_pk_log');
    assert.ok(table, 'no_pk_log should exist');
    assert.deepStrictEqual(table.primaryKey, [], 'no-PK table should have empty primaryKey array');
  });

  test('detects auto-generated columns', () => {
    const table = result.tables.find(t => t.name === 'exotic_types');
    assert.ok(table);
    assert.ok(table.autoGenerated.includes('id'), 'id should be auto-generated (gen_random_uuid)');
  });

  // ── Generation assertions ─────────────────────────────────────────────

  test('generateTypesFile produces valid output for migrated tables', () => {
    const migrated = result.tables.filter(t => !result.tablesUsingSupabaseAuth.has(t.name));
    const output = generateTypesFile(migrated);
    assert.ok(output.includes('export interface'), 'should produce interfaces');
    assert.ok(!output.includes('Todos'), 'should not include skipped todos');
    assert.ok(output.includes('ExoticTypes'), 'should include exotic_types');
    assert.ok(output.includes('ReservedCols'), 'should include reserved_cols');
  });

  test('generateMetaFile produces valid output', () => {
    const migrated = result.tables.filter(t => !result.tablesUsingSupabaseAuth.has(t.name));
    const output = generateMetaFile(migrated);
    assert.ok(output.includes('exotic_types:'), 'should include exotic_types meta');
    assert.ok(output.includes('reserved_cols:'), 'should include reserved_cols meta');
  });

  test('generateIndexFile produces valid output', () => {
    const migrated = result.tables.filter(t => !result.tablesUsingSupabaseAuth.has(t.name));
    const output = generateIndexFile(migrated, { projectRef: 'test', runtimeConnString: dbUrl! });
    // CRUD wiring is derived from tableMeta (PR #787), not a hardcoded list, so the
    // index doesn't name tables literally. Migrated tables are wired via tableMeta;
    // Supabase-auth tables are excluded upstream by being absent from tableMeta.
    assert.ok(
      output.includes('tables: Object.keys(tableMeta) as (keyof typeof tableMeta)[]'),
      'wires CRUD dynamically from tableMeta',
    );
  });

  // ── CRUD assertions (non-RLS tables) ──────────────────────────────────

  test('CRUD works on exotic_types table', async () => {
    const table = result.tables.find(t => t.name === 'exotic_types')!;
    const schema = {
      exotic_types: {
        singular: 'exoticType',
        plural: 'exoticTypes',
        primaryKey: table.primaryKey,
        columns: table.columns.map(c => c.column_name),
        autoGenerated: table.autoGenerated,
      },
    };

    const crud = createCrudHandlers(db, schema, {
      tables: ['exotic_types'],
      auth: async () => testUser,
    });

    // Create
    const row = await crud.createExoticType({ display_name: 'Test E2E', ip_address: '192.168.1.1' });
    assert.ok(row.id, 'should have auto-generated id');
    assert.strictEqual(row.display_name, 'Test E2E');

    // Read
    const fetched = await crud.getExoticType(row.id);
    assert.strictEqual(fetched.display_name, 'Test E2E');

    // Update
    const updated = await crud.updateExoticType(row.id, { display_name: 'Updated E2E' });
    assert.strictEqual(updated.display_name, 'Updated E2E');

    // Delete
    const deleted = await crud.deleteExoticType(row.id);
    assert.strictEqual(deleted.deleted, true);
  });

  test('CRUD works on reserved_cols table', async () => {
    const table = result.tables.find(t => t.name === 'reserved_cols')!;
    const schema = {
      reserved_cols: {
        singular: 'reservedCol',
        plural: 'reservedCols',
        primaryKey: table.primaryKey,
        columns: table.columns.map(c => c.column_name),
        autoGenerated: table.autoGenerated,
      },
    };

    const crud = createCrudHandlers(db, schema, {
      tables: ['reserved_cols'],
      auth: async () => testUser,
    });

    // Create with reserved-word columns
    const row = await crud.createReservedCol({ order: 42, group: 'test-group', select: true });
    assert.ok(row.id, 'should have auto-generated serial id');
    assert.strictEqual(row.order, 42);
    assert.strictEqual(row.group, 'test-group');
    assert.strictEqual(row.select, true);

    // Cleanup
    await crud.deleteReservedCol(row.id);
  });

  test('CRUD works on composite PK table', async () => {
    const table = result.tables.find(t => t.name === 'composite_pk_items')!;
    const schema = {
      composite_pk_items: {
        singular: 'compositePkItem',
        plural: 'compositePkItems',
        primaryKey: table.primaryKey,
        columns: table.columns.map(c => c.column_name),
        autoGenerated: table.autoGenerated,
      },
    };

    const crud = createCrudHandlers(db, schema, {
      tables: ['composite_pk_items'],
      auth: async () => testUser,
    });

    const orderId = crypto.randomUUID();
    const productId = crypto.randomUUID();
    const pk = { order_id: orderId, product_id: productId };

    // Create
    const row = await crud.createCompositePkItem({ ...pk, quantity: 3 });
    assert.strictEqual(row.order_id, orderId);
    assert.strictEqual(row.quantity, 3);

    // Get by composite key
    const fetched = await crud.getCompositePkItem(pk);
    assert.strictEqual(fetched.quantity, 3);

    // Update by composite key
    const updated = await crud.updateCompositePkItem(pk, { quantity: 7 });
    assert.strictEqual(updated.quantity, 7);

    // Delete by composite key
    const deleted = await crud.deleteCompositePkItem(pk);
    assert.strictEqual(deleted.deleted, true);

    // Verify string ID throws for composite PK
    await assert.rejects(
      () => crud.getCompositePkItem('some-string-id'),
      /Composite primary key requires an object/,
    );
  });
});
