// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { test } from 'node:test';
import assert from 'node:assert';
import { buildSelect, buildInsert, buildUpdate, buildDelete, buildWhere } from './sql-builder.js';
import type { TableMetaEntry } from './types.js';

const todosMeta: TableMetaEntry = {
  singular: 'todo',
  plural: 'todos',
  primaryKey: 'id',
  columns: ['id', 'content', 'done', 'priority', 'user_id', 'created_at', 'updated_at'],
  autoGenerated: ['id', 'created_at', 'updated_at'],
};

// ── buildSelect ────────────────────────────────────────────────────────

test('buildSelect: no opts returns SELECT *', () => {
  const q = buildSelect('todos', undefined, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos"');
  assert.deepStrictEqual(q.params, []);
});

test('buildSelect: select specific columns', () => {
  const q = buildSelect('todos', { select: ['id', 'content'] }, todosMeta);
  assert.strictEqual(q.text, 'SELECT "id", "content" FROM "todos"');
});

test('buildSelect: where equality', () => {
  const q = buildSelect('todos', { where: { done: false } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "done" = $1');
  assert.deepStrictEqual(q.params, [false]);
});

test('buildSelect: where gt operator', () => {
  const q = buildSelect('todos', { where: { priority: { gt: 3 } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "priority" > $1');
  assert.deepStrictEqual(q.params, [3]);
});

test('buildSelect: where gte operator', () => {
  const q = buildSelect('todos', { where: { priority: { gte: 5 } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "priority" >= $1');
  assert.deepStrictEqual(q.params, [5]);
});

test('buildSelect: where lt operator', () => {
  const q = buildSelect('todos', { where: { priority: { lt: 2 } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "priority" < $1');
  assert.deepStrictEqual(q.params, [2]);
});

test('buildSelect: where lte operator', () => {
  const q = buildSelect('todos', { where: { priority: { lte: 1 } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "priority" <= $1');
  assert.deepStrictEqual(q.params, [1]);
});

test('buildSelect: where like', () => {
  const q = buildSelect('todos', { where: { content: { like: '%milk%' } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "content" LIKE $1');
  assert.deepStrictEqual(q.params, ['%milk%']);
});

test('buildSelect: where ilike', () => {
  const q = buildSelect('todos', { where: { content: { ilike: '%MILK%' } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "content" ILIKE $1');
  assert.deepStrictEqual(q.params, ['%MILK%']);
});

test('buildSelect: where in', () => {
  const q = buildSelect('todos', { where: { priority: { in: [1, 2, 3] } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "priority" IN ($1, $2, $3)');
  assert.deepStrictEqual(q.params, [1, 2, 3]);
});

test('buildSelect: where IS NULL', () => {
  const q = buildSelect('todos', { where: { content: null } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "content" IS NULL');
  assert.deepStrictEqual(q.params, []);
});

test('buildSelect: multiple where conditions (AND)', () => {
  const q = buildSelect('todos', { where: { done: false, priority: { gt: 3 } } as any }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE "done" = $1 AND "priority" > $2');
  assert.deepStrictEqual(q.params, [false, 3]);
});

test('buildSelect: or clause', () => {
  const q = buildSelect('todos', {
    where: { or: [{ done: true }, { priority: { gt: 5 } }] } as any,
  }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" WHERE ("done" = $1 OR "priority" > $2)');
  assert.deepStrictEqual(q.params, [true, 5]);
});

test('buildSelect: orderBy single', () => {
  const q = buildSelect('todos', { orderBy: 'created_at:desc' }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" ORDER BY "created_at" DESC');
});

test('buildSelect: orderBy multiple', () => {
  const q = buildSelect('todos', { orderBy: ['priority:desc', 'created_at:asc'] }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" ORDER BY "priority" DESC, "created_at" ASC');
});

test('buildSelect: limit and offset', () => {
  const q = buildSelect('todos', { limit: 20, offset: 40 }, todosMeta);
  assert.strictEqual(q.text, 'SELECT * FROM "todos" LIMIT $1 OFFSET $2');
  assert.deepStrictEqual(q.params, [20, 40]);
});

test('buildSelect: full query with all options', () => {
  const q = buildSelect('todos', {
    select: ['id', 'content', 'done'],
    where: { done: false, priority: { gt: 3 } } as any,
    orderBy: ['created_at:desc'],
    limit: 20,
    offset: 0,
  }, todosMeta);
  assert.strictEqual(
    q.text,
    'SELECT "id", "content", "done" FROM "todos" WHERE "done" = $1 AND "priority" > $2 ORDER BY "created_at" DESC LIMIT $3 OFFSET $4',
  );
  assert.deepStrictEqual(q.params, [false, 3, 20, 0]);
});

test('buildSelect: unknown column throws', () => {
  assert.throws(
    () => buildSelect('todos', { where: { nonexistent: true } as any }, todosMeta),
    /Unknown column: "nonexistent"/,
  );
});

test('buildSelect: unknown select column throws', () => {
  assert.throws(
    () => buildSelect('todos', { select: ['bad_col'] as any }, todosMeta),
    /Unknown column: "bad_col"/,
  );
});

test('buildSelect: unknown orderBy column throws', () => {
  assert.throws(
    () => buildSelect('todos', { orderBy: 'bad_col:asc' }, todosMeta),
    /Unknown column: "bad_col"/,
  );
});

test('buildSelect: negative limit throws', () => {
  assert.throws(
    () => buildSelect('todos', { limit: -1 }, todosMeta),
    /limit must be a non-negative integer/,
  );
});

test('buildSelect: negative offset throws', () => {
  assert.throws(
    () => buildSelect('todos', { offset: -5 }, todosMeta),
    /offset must be a non-negative integer/,
  );
});

test('buildSelect: unknown operator throws', () => {
  assert.throws(
    () => buildSelect('todos', { where: { priority: { badOp: 1 } } as any }, todosMeta),
    /Unknown operator: "badOp"/,
  );
});

test('buildSelect: in with empty array throws', () => {
  assert.throws(
    () => buildSelect('todos', { where: { priority: { in: [] } } as any }, todosMeta),
    /"in" requires a non-empty array/,
  );
});

// ── buildInsert ────────────────────────────────────────────────────────

test('buildInsert: basic insert excludes auto-generated', () => {
  const q = buildInsert('todos', { content: 'Buy milk', done: false, user_id: 'u1' }, todosMeta);
  assert.strictEqual(q.text, 'INSERT INTO "todos" ("content", "done", "user_id") VALUES ($1, $2, $3) RETURNING *');
  assert.deepStrictEqual(q.params, ['Buy milk', false, 'u1']);
});

test('buildInsert: auto-generated columns are excluded', () => {
  const q = buildInsert('todos', { id: 'manual', content: 'test', done: true, user_id: 'u1' }, todosMeta);
  // id is auto-generated, should be excluded
  assert.ok(!q.text.includes('"id"'));
  assert.deepStrictEqual(q.params, ['test', true, 'u1']);
});

test('buildInsert: all auto-generated throws', () => {
  assert.throws(
    () => buildInsert('todos', { id: 'x', created_at: 'now', updated_at: 'now' }, todosMeta),
    /No columns to insert/,
  );
});

test('buildInsert: unknown column throws', () => {
  assert.throws(
    () => buildInsert('todos', { bad_col: 'x' }, todosMeta),
    /Unknown column: "bad_col"/,
  );
});

// ── buildUpdate ────────────────────────────────────────────────────────

test('buildUpdate: partial update', () => {
  const q = buildUpdate('todos', ['todo-1'], { done: true }, todosMeta);
  assert.strictEqual(q.text, 'UPDATE "todos" SET "done" = $1 WHERE "id" = $2 RETURNING *');
  assert.deepStrictEqual(q.params, [true, 'todo-1']);
});

test('buildUpdate: multiple fields', () => {
  const q = buildUpdate('todos', ['todo-1'], { content: 'Updated', done: true }, todosMeta);
  assert.strictEqual(q.text, 'UPDATE "todos" SET "content" = $1, "done" = $2 WHERE "id" = $3 RETURNING *');
  assert.deepStrictEqual(q.params, ['Updated', true, 'todo-1']);
});

test('buildUpdate: auto-generated columns excluded', () => {
  const q = buildUpdate('todos', ['todo-1'], { content: 'x', updated_at: 'now' }, todosMeta);
  assert.ok(!q.text.includes('"updated_at"'));
  assert.deepStrictEqual(q.params, ['x', 'todo-1']);
});

test('buildUpdate: empty data throws', () => {
  assert.throws(
    () => buildUpdate('todos', ['todo-1'], {}, todosMeta),
    /No columns to update/,
  );
});

// ── buildDelete ────────────────────────────────────────────────────────

test('buildDelete: basic delete', () => {
  const q = buildDelete('todos', ['todo-1'], todosMeta);
  assert.strictEqual(q.text, 'DELETE FROM "todos" WHERE "id" = $1');
  assert.deepStrictEqual(q.params, ['todo-1']);
});

// ── Composite primary key ──────────────────────────────────────────────

const compositeMeta: TableMetaEntry = {
  singular: 'enrollment',
  plural: 'enrollments',
  primaryKey: ['student_id', 'course_id'],
  columns: ['student_id', 'course_id', 'grade'],
  autoGenerated: [],
};

test('buildUpdate: composite PK generates AND clause', () => {
  const q = buildUpdate('enrollments', ['s1', 'c1'], { grade: 'A' }, compositeMeta);
  assert.strictEqual(q.text, 'UPDATE "enrollments" SET "grade" = $1 WHERE "student_id" = $2 AND "course_id" = $3 RETURNING *');
  assert.deepStrictEqual(q.params, ['A', 's1', 'c1']);
});

test('buildDelete: composite PK generates AND clause', () => {
  const q = buildDelete('enrollments', ['s1', 'c1'], compositeMeta);
  assert.strictEqual(q.text, 'DELETE FROM "enrollments" WHERE "student_id" = $1 AND "course_id" = $2');
  assert.deepStrictEqual(q.params, ['s1', 'c1']);
});

// ── SQL injection defense ──────────────────────────────────────────────

test('identifiers with special chars are escaped', () => {
  const meta: TableMetaEntry = {
    singular: 'item',
    plural: 'items',
    primaryKey: 'id',
    columns: ['id', 'col"name'],
    autoGenerated: ['id'],
  };
  const q = buildSelect('items', { select: ['col"name'] as any }, meta);
  assert.strictEqual(q.text, 'SELECT "col""name" FROM "items"');
});

// ─── buildWhere — or-clause operator validation ─────────────────────────────
// The `or` branch must validate operator inputs the same way the top-level
// branch does. Empty/non-array `in` values must be rejected, not produce
// invalid SQL or uncaught TypeErrors.

test('buildWhere: empty "in" array at top level throws (control)', () => {
  assert.throws(
    () => buildWhere({ priority: { in: [] } } as any, todosMeta),
    /"in" requires a non-empty array/,
  );
});

test('buildWhere: empty "in" array inside "or" throws (not invalid SQL)', () => {
  assert.throws(
    () => buildWhere({ or: [{ priority: { in: [] } }] } as any, todosMeta),
    /"in" requires a non-empty array/,
  );
});

test('buildWhere: non-array "in" value inside "or" throws (not an uncaught TypeError)', () => {
  assert.throws(
    () => buildWhere({ or: [{ priority: { in: 'not-an-array' } }] } as any, todosMeta),
    /"in" requires a non-empty array/,
  );
});

test('buildWhere: valid "in" inside "or" still builds correctly', () => {
  const { clause, params } = buildWhere(
    { or: [{ priority: { in: [1, 2] } }, { done: true }] } as any,
    todosMeta,
  );
  assert.ok(clause.includes('IN ($1, $2)'), `expected IN with two params, got: ${clause}`);
  assert.deepStrictEqual(params, [1, 2, true]);
});

test('buildWhere: unknown operator inside "or" throws (parity with top level)', () => {
  assert.throws(
    () => buildWhere({ or: [{ priority: { bogus: 1 } }] } as any, todosMeta),
    /Unknown operator: "bogus"/,
  );
});

// ─── buildSelect — orderBy direction validation ─────────────────────────────
// orderBy must be in "column:asc" or "column:desc" format. Invalid directions,
// missing directions, and extra colon segments must be rejected.

test('buildSelect: invalid orderBy direction throws instead of defaulting to ASC', () => {
  assert.throws(
    () => buildSelect('todos', { orderBy: 'priority:invalid' }, todosMeta),
    /direction/i,
  );
});

test('buildSelect: orderBy with extra colon segment throws', () => {
  assert.throws(
    () => buildSelect('todos', { orderBy: 'priority:desc:extra' }, todosMeta),
    /direction|orderBy/i,
  );
});

test('buildSelect: orderBy without a direction throws (must be explicit asc/desc)', () => {
  assert.throws(
    () => buildSelect('todos', { orderBy: 'priority' }, todosMeta),
    /direction|orderBy/i,
  );
});

test('buildSelect: valid asc/desc directions still work', () => {
  assert.strictEqual(
    buildSelect('todos', { orderBy: 'priority:asc' }, todosMeta).text,
    'SELECT * FROM "todos" ORDER BY "priority" ASC',
  );
  assert.strictEqual(
    buildSelect('todos', { orderBy: 'priority:DESC' }, todosMeta).text,
    'SELECT * FROM "todos" ORDER BY "priority" DESC',
  );
});
