// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Types for the CRUD filter DSL and table metadata.
 *
 * The filter DSL provides Supabase-parity filtering, sorting, pagination,
 * and column selection for `db.crud()` generated handlers.
 */

/** Comparison operators for filter expressions. */
export type Operator<T> = {
  gt?: T;
  gte?: T;
  lt?: T;
  lte?: T;
  like?: string;
  ilike?: string;
  in?: T[];
};

/** WHERE clause — each key is a column, value is either direct equality or an operator object. null = IS NULL. */
export type WhereClause<Row> = {
  [K in keyof Row]?: Row[K] | Operator<Row[K]> | null;
} & {
  or?: WhereClause<Row>[];
};

/** Query options for list operations. */
export interface QueryOpts<Row> {
  where?: WhereClause<Row>;
  orderBy?: string | string[];
  limit?: number;
  offset?: number;
  select?: (keyof Row & string)[];
}

/** Output of the SQL builder — parameterized query text + values. */
export interface BuiltQuery {
  text: string;
  params: unknown[];
}

/** Runtime metadata for a single table. */
export interface TableMetaEntry {
  singular: string;
  plural: string;
  primaryKey: string | string[];
  columns: readonly string[];
  autoGenerated: readonly string[];
}

/** Runtime schema registry — one entry per table. */
export type TableSchema = Record<string, TableMetaEntry>;

/**
 * Type-level metadata for a single table.
 * Used by the CrudMethods mapped type to derive method signatures.
 */
export interface TableTypeMeta {
  row: Record<string, unknown>;
  singular: string;
  plural: string;
  autoGenerated: string;
}

/** Auth result expected by crud() — any auth BB returning { userId } satisfies this. */
export interface CrudAuthResult {
  userId: string;
  claims?: Record<string, unknown>;
}

/** Options for db.crud(). */
export interface CrudOptions<M extends Record<string, TableTypeMeta>> {
  tables: (keyof M & string)[];
  auth: () => Promise<CrudAuthResult>;
  exclude?: string[];
}

/** Mapped type: generates CRUD method signatures from table metadata. */
export type CrudMethods<
  M extends Record<string, TableTypeMeta>,
  Tables extends keyof M & string = keyof M & string,
> = UnionToIntersection<
  Tables extends infer T extends keyof M & string
    ? { [K in `list${Capitalize<M[T]['plural']>}`]: (opts?: QueryOpts<M[T]['row']>) => Promise<M[T]['row'][]> } &
      { [K in `get${Capitalize<M[T]['singular']>}`]: (id: string | Record<string, unknown>) => Promise<M[T]['row'] | null> } &
      { [K in `create${Capitalize<M[T]['singular']>}`]: (data: Omit<M[T]['row'], M[T]['autoGenerated']>) => Promise<M[T]['row']> } &
      { [K in `update${Capitalize<M[T]['singular']>}`]: (id: string | Record<string, unknown>, data: Partial<Omit<M[T]['row'], M[T]['autoGenerated']>>) => Promise<M[T]['row'] | null> } &
      { [K in `delete${Capitalize<M[T]['singular']>}`]: (id: string | Record<string, unknown>) => Promise<{ deleted: boolean }> }
    : never
>;

/** Helper: converts a union to an intersection. */
type UnionToIntersection<U> = (U extends unknown ? (k: U) => void : never) extends (k: infer I) => void ? I : never;
