// ============================================================
// AUTO-GENERATED FILE — DO NOT EDIT
//
// This file is generated by the Blocks dev server / build process.
// Any manual changes will be overwritten on the next build.
// ============================================================

import { ApiNamespaceClient as __BLOCKS_ApiNamespaceClient__ } from '@aws-blocks/blocks/client';

export const hello = __BLOCKS_ApiNamespaceClient__('hello');
export const authApi = __BLOCKS_ApiNamespaceClient__('authApi');
export const api = __BLOCKS_ApiNamespaceClient__('api');

export const generateClient = (config) => ({
    hello: __BLOCKS_ApiNamespaceClient__('hello', config),
    authApi: __BLOCKS_ApiNamespaceClient__('authApi', config),
    api: __BLOCKS_ApiNamespaceClient__('api', config),
});
