#!/usr/bin/env node
/**
 * Generates src/version.ts for a Building Block package or @aws-blocks/core.
 *
 * Usage:
 *   node scripts/generate-version.mjs <bbName>    — for a BB package (writes BB_NAME + BB_VERSION)
 *   node scripts/generate-version.mjs --core      — for @aws-blocks/core (writes CORE_VERSION)
 *
 * For BBs: reads the package's own version and writes BB_NAME and BB_VERSION.
 * For core: reads core's own version and writes CORE_VERSION.
 *
 * CORE_VERSION is no longer baked into BB packages — BBs import it from
 * @aws-blocks/core at runtime. This prevents BB tarballs from changing
 * when only core's version bumps.
 *
 * Designed to be called from each package's `prebuild` npm script.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const arg = process.argv[2];
if (!arg) {
	console.error('Usage: node scripts/generate-version.mjs <BbName>');
	console.error('       node scripts/generate-version.mjs --core');
	process.exit(1);
}

const pkgDir = process.cwd();

if (arg === '--core') {
	// Generate version.ts for @aws-blocks/core itself
	const corePkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf-8'));
	const content = `// Auto-generated by scripts/generate-version.mjs — do not edit manually\nexport const CORE_VERSION = '${corePkg.version}';\n`;
	writeFileSync(join(pkgDir, 'src', 'version.ts'), content);
	console.log(`Generated core version.ts: ${corePkg.version}`);
} else {
	// Generate version.ts for a Building Block
	const bbName = arg;
	const bbPkg = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf-8'));

	const content = `// Auto-generated by scripts/generate-version.mjs — do not edit manually
export const BB_NAME = '${bbName}';
export const BB_VERSION = '${bbPkg.version}';
`;

	writeFileSync(join(pkgDir, 'src', 'version.ts'), content);
	console.log(`Generated version.ts: bb/${bbName}/${bbPkg.version}`);
}
