// DO NOT EDIT — auto-generated by scripts/generate-bb-names.mjs
// Source: packages/blocks/package.json → aws-blocks.vendorize

/**
 * Set of official Building Block display names recognized by telemetry.
 * Any BB whose `bbName` matches one of these entries is reported in the
 * `product.buildingBlocks` array; others still contribute to `totalCount`.
 */
export const OFFICIAL_BB_NAMES: ReadonlySet<string> = new Set([
  'Agent',
  'AppSetting',
  'AsyncJob',
  'AuthBasic',
  'AuthCognito',
  'AuthOidc',
  'CronJob',
  'Dashboard',
  'Database',
  'DistributedDatabase',
  'DistributedTable',
  'EmailClient',
  'FileBucket',
  'KVStore',
  'KnowledgeBase',
  'Logger',
  'Metrics',
  'OtelLogger',
  'OtelMetrics',
  'OtelTracer',
  'Realtime',
  'Tracer',
]);
