// ============================================================
// AUTO-GENERATED FILE — DO NOT EDIT
//
// This file is generated by the Blocks dev server / build process.
// Any manual changes will be overwritten on the next build.
// ============================================================

import { ApiNamespaceClient as __BLOCKS_ApiNamespaceClient__ } from '@aws-blocks/blocks/client';
import '@aws-blocks/bb-auth-oidc/middleware';
import '@aws-blocks/bb-realtime/mock-middleware';
import '@aws-blocks/bb-file-bucket/middleware';

export const api = __BLOCKS_ApiNamespaceClient__('api');
export const authBasicApi = __BLOCKS_ApiNamespaceClient__('authBasicApi');
export const authCognitoApi = __BLOCKS_ApiNamespaceClient__('authCognitoApi');
export const oidcAuthApi = __BLOCKS_ApiNamespaceClient__('oidcAuthApi');

export const generateClient = (config) => ({
    api: __BLOCKS_ApiNamespaceClient__('api', config),
    authBasicApi: __BLOCKS_ApiNamespaceClient__('authBasicApi', config),
    authCognitoApi: __BLOCKS_ApiNamespaceClient__('authCognitoApi', config),
    oidcAuthApi: __BLOCKS_ApiNamespaceClient__('oidcAuthApi', config),
});